package main

import (
	"os"
	"strings"
	"testing"
)

func TestWindowsInstallerDefaults(t *testing.T) {
	data, err := os.ReadFile("install-windows.ps1")
	if err != nil {
		t.Fatal(err)
	}
	script := string(data)
	for _, needle := range []string{
		`param(`,
		`[ValidatePattern('^[A-Za-z0-9_.-]+$')]`,
		`[ValidateRange(1, 65535)]`,
		`[ValidateRange(1, 300)]`,
		`$ReadinessTimeoutSeconds = 20`,
		`$ServiceName = 'HomelabSysmonAgent'`,
		`$SettingsPath = "$env:ProgramData\SysmonAgent\settings.json"`,
		`-Profile Domain,Private`,
		`Command-line values cannot contain double quotes`,
		`function Resolve-HealthHost`,
		`function Format-UrlHost`,
		`function Test-UsableDeviceHost`,
		`function Test-DeviceInterfaceName`,
		`InterfaceAlias`,
		`Test-DeviceInterfaceName ([string]$_.InterfaceAlias)`,
		`if ($hosts.Count -eq 0)`,
		`'vethernet'`,
		`'wsl'`,
		`function Get-DeviceHostPriority`,
		`function Get-CandidateDeviceHosts`,
		`function Get-DeviceUrls`,
		`function Show-DeviceHandoff`,
		`Get-NetIPAddress`,
		`http://$(Format-UrlHost $_):$Port/`,
		`Sysmon device URLs:`,
		`Final Sysmon device verification:`,
		`.\verify-deployed-windows.ps1 -HoldSeconds 120`,
		`Add the Sysmon URL to your device Home Screen, then open that Home Screen app and tap the status strip during the hold.`,
		`function Get-ReadinessCheckUrl`,
		`function Get-StatusCheckUrl`,
		`function Get-AgentBaseUrl`,
		`function Wait-AgentReady`,
		`Invoke-RestMethod -Method Get -Uri $readyUrl -TimeoutSec 4`,
		`Readiness check ok: $readyUrl`,
		`did not become ready at $readyUrl within ${ReadinessTimeoutSeconds}s`,
		`function Show-AgentReadiness`,
		`Dashboard readiness ok: $readyUrl`,
		`Dashboard readiness failed at ${readyUrl}`,
		`function Format-OnOff`,
		`function Show-DashboardSettings`,
		`Invoke-RestMethod -Method Get -Uri $statusUrl -TimeoutSec 4`,
		`$dashboardBuild = if ([string]::IsNullOrWhiteSpace([string]$status.dashboard_build)) { 'unknown' } else { [string]$status.dashboard_build }`,
		`Dashboard settings: $persistence, build=$dashboardBuild, refresh=$($settings.refresh_ms)ms, panel=$($settings.panel), dim=$(Format-OnOff $settings.dim), shift=$(Format-OnOff $settings.shift)`,
		`thresholds: CPU $($settings.thresholds.cpu_warn)% / RAM $($settings.thresholds.memory_warn)% / Disk $($settings.thresholds.disk_warn)% / GPU $($settings.thresholds.gpu_warn)% / Temp $($settings.thresholds.temp_warn_c)C`,
		`Dashboard settings unavailable at ${statusUrl}`,
		`Dashboard settings failed at ${statusUrl}`,
		`function Test-DeviceClientCheckEvidence`,
		`$mobileDevice = $userAgent.Contains('Mobile') -or $userAgent.Contains('iPhone') -or $userAgent.Contains('iPad') -or $userAgent.Contains('iPod') -or $userAgent.Contains('Android')`,
		`function Test-StandaloneClientCheckEvidence`,
		`function Test-InteractionClientCheckEvidence`,
		`function Get-TimeMilliseconds`,
		`function Get-ClientCheckAgeSeconds`,
		`function Test-ClientCheckStale`,
		`SYSMON_STATUS_CLIENT_FRESH_SECONDS`,
		`function Get-CurrentDashboardBuild`,
		`function Get-ClientCheckRank`,
		`function Get-BestClientCheck`,
		`function Get-StatusClientCheck`,
		`function Get-LatestHomeScreenClientCheck`,
		`function Get-ClientCheckIdentityKey`,
		`function Show-RecentHomeScreenActivity`,
		`$status.device_client_check`,
		`$status.client_check`,
		`function Show-ClientCheckStatus`,
		`$historyUrl = "$baseUrl/api/client-checks"`,
		`$latestUrl = "$baseUrl/api/client-check"`,
		`$statusClientCheck = Get-StatusClientCheck`,
		`$latestHomeScreenClientCheck = Get-LatestHomeScreenClientCheck $entries`,
		`$selectedClientCheck = Get-BestClientCheck @($clientCheck, $statusClientCheck)`,
		`$selectedHomeScreenClientCheck = Get-LatestHomeScreenClientCheck @($latestHomeScreenClientCheck, $statusClientCheck)`,
		`[object]::ReferenceEquals($selectedClientCheck, $statusClientCheck)`,
		`$url = Get-StatusCheckUrl`,
		`device client: not observed yet`,
		`device client: $label Home Screen stale at`,
		`device client: $label Home Screen stale dashboard build at`,
		`device client: $label Home Screen status-strip tap seen at`,
		`Show-RecentHomeScreenActivity $clientCheck $latestHomeScreenClientCheck`,
		`device client: recent Home Screen activity at`,
		`device client: $label Home Screen seen without status-strip tap at`,
		`function Resolve-IntEnv`,
		`SYSMON_DEPLOY_VERIFY_REPORT_FRESH_SECONDS`,
		`function Get-DeployedReportPath`,
		`SYSMON_DEPLOY_VERIFY_REPORT`,
		`sysmon-agent-deployed-verify-report.txt`,
		`function Get-DeployedReportField`,
		`function Get-ReportAgeSeconds`,
		`function Show-DeployedReportUrl`,
		`$deviceUrl = Get-DeployedReportField $ReportPath 'device_url'`,
		`$deviceUrlSource = Get-DeployedReportField $ReportPath 'device_url_source'`,
		`Last device URL: $deviceUrl$sourceLabel`,
		`function Show-DeployedDeviceGate`,
		`$clientSeen = Get-DeployedReportField $reportPath 'device_client_seen'`,
		`$clientInteraction = Get-DeployedReportField $reportPath 'device_client_interaction'`,
		`$dashboardBuild = Get-DeployedReportField $reportPath 'dashboard_build'`,
		`$detailParts += "client=$clientSeen"`,
		`$detailParts += "interaction=$clientInteraction"`,
		`$detailParts += "build=$dashboardBuild"`,
		`Last deployed device gate: no report`,
		`Last deployed device gate: unreadable report`,
		`Last deployed device gate: pass but stale`,
		`Show-DeployedReportUrl $reportPath`,
		`.\verify-deployed-windows.ps1 -HoldSeconds 120`,
		`function Remove-ServiceFirewallRules`,
		`Get-NetFirewallRule -Name "$ServiceName-*"`,
		`$rules | Remove-NetFirewallRule`,
		`Remove-ServiceFirewallRules`,
		`function Set-ServiceRecovery`,
		`sc.exe failure $ServiceName reset= 86400 actions= restart/5000/restart/5000/restart/30000`,
		`sc.exe failureflag $ServiceName 1`,
		`Set-ServiceRecovery`,
		`Wait-AgentReady`,
		`Show-AgentReadiness`,
		`Show-DashboardSettings`,
		`Show-ClientCheckStatus`,
		`Show-DeployedDeviceGate`,
		`Show-DeviceHandoff`,
		`$serviceInstalled = $false`,
	} {
		if !strings.Contains(script, needle) {
			t.Fatalf("install-windows.ps1 missing %q", needle)
		}
	}
}

func TestWindowsVerifierDefaults(t *testing.T) {
	data, err := os.ReadFile("verify-windows.ps1")
	if err != nil {
		t.Fatal(err)
	}
	script := string(data)
	for _, needle := range []string{
		`param(`,
		`$Bind = '127.0.0.1'`,
		`$CheckHost = ''`,
		`$DeviceUrl = ''`,
		`[switch]$RequireDevice`,
		`[ValidateRange(1, 65535)]`,
		`[ValidateRange(0, 86400)]`,
		`$HoldSeconds = 0`,
		`$AgentPath = Join-Path $TempRoot 'sysmon-agent.exe'`,
		`$ReportPath = if ($env:SYSMON_VERIFY_REPORT)`,
		`sysmon-agent-verify-report.txt`,
		`configured_device_url=$DeviceUrl`,
		`require_device=$($RequireDevice.IsPresent.ToString().ToLowerInvariant())`,
		`installed_device_home_screen=not_verified`,
		`function Write-Report`,
		`function Write-ClientCheckReport`,
		`function Write-ReadinessCollectionErrors`,
		`${Prefix}_collection_errors=none`,
		`${Prefix}_collection_error_$($i + 1)=$($errors[$i])`,
		`'screen_width', 'screen_height'`,
		`'touch_points'`,
		`'display_mode'`,
		`'orientation'`,
		`function Test-DeviceClientCheckEvidence`,
		`$mobileDevice = $userAgent.Contains('Mobile') -or $userAgent.Contains('iPhone') -or $userAgent.Contains('iPad') -or $userAgent.Contains('iPod') -or $userAgent.Contains('Android')`,
		`$userAgent.Contains('Mobile')`,
		`function Get-TimeMilliseconds`,
		`function Test-FreshClientCheck`,
		`(Test-FreshClientCheck $clientCheckAfter) -and $null -eq $seenClientCheck`,
		`$HoldStartedMs = $null`,
		`$env:GOCACHE = Join-Path ([System.IO.Path]::GetTempPath()) 'go-build-cache'`,
		`go build -o $AgentPath .`,
		`Get-Command node`,
		`node verify-dashboard.mjs`,
		`node verify-api.mjs --settings-roundtrip $BaseUrl`,
		`node verify-render.mjs`,
		`'"dashboard_build"'`,
		`Write-Report 'api_schema=pass'`,
		`Write-Report 'dashboard_render=pass'`,
		`Write-Report 'dashboard_render=skipped_browser_unavailable'`,
		`Write-Report 'dashboard_assets=pass'`,
		`function Invoke-Headers`,
		`function Assert-HeaderContains`,
		`Assert-HeaderContains "$BaseUrl/api/status" 'Cache-Control' 'no-store'`,
		`Assert-HeaderContains "$BaseUrl/api/status" 'Content-Security-Policy' "default-src 'self'"`,
		`Assert-HeaderContains "$BaseUrl/" 'Cache-Control' 'no-cache'`,
		`Assert-HeaderContains "$BaseUrl/" 'X-Content-Type-Options' 'nosniff'`,
		`function Resolve-CheckHost`,
		`function Format-UrlHost`,
		`function Test-DeviceInterfaceName`,
		`InterfaceAlias`,
		`Test-DeviceInterfaceName ([string]$_.InterfaceAlias)`,
		`if ($addresses.Count -eq 0)`,
		`'vethernet'`,
		`'wsl'`,
		`function Get-DeviceHostPriority`,
		`$bytes[0] -eq 100 -and $bytes[1] -ge 64 -and $bytes[1] -le 127`,
		`($bytes[0] -band 0xfe) -eq 0xfc`,
		`function Resolve-DeviceHosts`,
		`Get-NetIPAddress`,
		`Sort-Object @{ Expression = { Get-DeviceHostPriority $_ }; Ascending = $true }`,
		`function Write-DeviceUrls`,
		`function Get-DeviceUrls`,
		`http://$(Format-UrlHost $hostName):$Port/`,
		`Write-Host "  $DeviceUrl"`,
		`Write-Report "device_url=$DeviceUrl"`,
		`Write-Report "device_url=$url"`,
		`For a device check, rerun with -Bind 0.0.0.0 -HoldSeconds 120 -RequireDevice.`,
		`Verification report: $ReportPath`,
		`Write-Report 'result=pass'`,
		`Starting sysmon-agent on ${Bind}:$Port; checking $BaseUrl`,
		`Write-Report 'agent_spawned=pass'`,
		`Write-Report 'agent_ready=fail'`,
		`Write-Report 'agent_ready=pass'`,
		`$script:HoldStartedMs = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()`,
		`Write-Report "hold_started_ms=$script:HoldStartedMs"`,
		`Start-Sleep -Seconds $HoldSeconds`,
		`/api/metrics`,
		`/readyz`,
		`/api/status`,
		`/api/settings`,
		`/api/client-check`,
		`/api/client-checks`,
		`Checking /api/client-check`,
		`Write-Report 'client_check=pass'`,
		`Write-Report 'readyz=pass'`,
		`Write-ReadinessCollectionErrors 'readyz'`,
		`function Get-ClientCheckEntries`,
		`function Get-StatusClientCheckEntries`,
		`$status.device_client_check`,
		`$status.client_check`,
		`$entries += Get-StatusClientCheckEntries $Url`,
		`foreach ($clientCheckAfter in @(Get-ClientCheckEntries $BaseUrl))`,
		`Test-FreshClientCheck $clientCheckAfter`,
		`Write-Report 'device_client_seen=pass'`,
		`Write-ClientCheckReport $deviceClientCheck`,
		`Write-ClientCheckReport $staleDeviceClientCheck`,
		`Write-Report 'device_client_seen=stale_client'`,
		`Write-ClientCheckReport $seenClientCheck`,
		`Write-Report 'device_client_seen=unexpected_client'`,
		`required device client check was not observed`,
		`Write-Report 'device_client_seen=not_observed'`,
		`Write-Report 'device_client_seen=not_attempted_loopback_bind'`,
		`required device client check cannot run on a loopback-only bind`,
		`Write-Report 'device_client_seen=not_attempted'`,
		`required device client check needs -HoldSeconds greater than zero`,
		`Checking live API schema`,
		`live API schema validation failed`,
		`Checking settings readback and persistence`,
		`-Headers @{ Origin = $BaseUrl }`,
		`$settingsReadback = Invoke-RestMethod`,
		`-Method Get`,
		`"shift":\s*true`,
		`settings file was not written`,
		`"panel":\s*"gpu"`,
		`"cpu_warn":\s*80`,
		`"temp_warn_c":\s*75`,
		`unexpected threshold settings response`,
		`unexpected threshold settings readback`,
		`fetchMetrics`,
		`isLiveEndpoint`,
		`sysmon-agent Windows smoke test passed`,
	} {
		if !strings.Contains(script, needle) {
			t.Fatalf("verify-windows.ps1 missing %q", needle)
		}
	}
}

func TestWindowsDeployedVerifierDefaults(t *testing.T) {
	data, err := os.ReadFile("verify-deployed-windows.ps1")
	if err != nil {
		t.Fatal(err)
	}
	script := string(data)
	for _, needle := range []string{
		`param(`,
		`$BaseUrl = ''`,
		`$DeviceUrl = ''`,
		`[ValidateRange(0, 86400)]`,
		`$HoldSeconds = 120`,
		`$RequireDevice = $true`,
		`$RequireStandalone = $true`,
		`SYSMON_DEPLOY_VERIFY_BASE_URL`,
		`SYSMON_DEPLOY_VERIFY_DEVICE_URL`,
		`SYSMON_DEPLOY_VERIFY_REQUIRE_STANDALONE`,
		`sysmon-agent-deployed-verify-report.txt`,
		`function Test-PwaInstallAssets`,
		`function Test-PngDimensions`,
		`function Test-SettingsSameOriginRoundTrip`,
		`function Test-ClientCheckSameOriginRoundTrip`,
		`-Headers @{ Origin = $Url }`,
		`thresholds = [ordered]@{`,
		`settings thresholds.$key roundtrip mismatch`,
		`$statusAfterSettings = Invoke-RestMethod -Method Get -Uri "$Url/api/status" -TimeoutSec 5`,
		`$statusSettings = $statusAfterSettings.settings`,
		`settings status.$key roundtrip mismatch`,
		`settings status.thresholds.$key roundtrip mismatch`,
		`Checking published interactive settings controls`,
		`Write-Report 'public_settings_roundtrip=pass'`,
		`Checking published client-check controls`,
		`dashboard_build = $script:ExpectedDashboardBuild`,
		`foreach ($key in @('dashboard_build',`,
		`$statusAfterClientCheck = Invoke-RestMethod -Method Get -Uri "$Url/api/status" -TimeoutSec 5`,
		`$statusClientCheck = $statusAfterClientCheck.client_check`,
		`status client_check $key roundtrip mismatch`,
		`Write-Report 'public_client_check_roundtrip=pass'`,
		`<link rel="manifest" href="/manifest.json">`,
		`<link rel="apple-touch-icon" sizes="180x180" href="/icon-180.png">`,
		`<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">`,
		`<meta name="apple-mobile-web-app-capable" content="yes">`,
		`<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">`,
		`<meta name="apple-mobile-web-app-title" content="Sysmon">`,
		`'"id"\s*:\s*"/"'`,
		`'"display"\s*:\s*"standalone"'`,
		`'"background_color"\s*:\s*"#080b10"'`,
		`'"theme_color"\s*:\s*"#080b10"'`,
		`'"src"\s*:\s*"/icon-512.png"'`,
		`Test-PngDimensions "$Url/icon-180.png" 180`,
		`Test-PngDimensions "$Url/icon-512.png" 512`,
		`'display_mode'`,
		`function Test-DeviceClientCheckEvidence`,
		`$mobileDevice = $userAgent.Contains('Mobile') -or $userAgent.Contains('iPhone') -or $userAgent.Contains('iPad') -or $userAgent.Contains('iPod') -or $userAgent.Contains('Android')`,
		`function Test-StandaloneClientCheckEvidence`,
		`[string]$ClientCheck.display_mode -eq 'standalone'`,
		`function Test-InteractionClientCheckEvidence`,
		`[string]$ClientCheck.interaction`,
		`[bool]$RequireInteraction = $true`,
		`SYSMON_DEPLOY_VERIFY_REQUIRE_INTERACTION`,
		`require_interaction=$($RequireInteraction.ToString().ToLowerInvariant())`,
		`function Test-CurrentDashboardBuildEvidence`,
		`[string]$ClientCheck.dashboard_build -eq $script:ExpectedDashboardBuild`,
		`function Test-FreshClientCheck`,
		`function Write-ReadinessCollectionErrors`,
		`${Prefix}_collection_errors=none`,
		`${Prefix}_collection_error_$($i + 1)=$($errors[$i])`,
		`function Write-ClientCheckResult`,
		`if (-not (Test-FreshClientCheck $ClientCheck))`,
		`function Get-ClientCheckEntries`,
		`/api/client-checks`,
		`function Get-StatusClientCheckEntries`,
		`$status.device_client_check`,
		`$status.client_check`,
		`$entries += Get-StatusClientCheckEntries $BaseUrl`,
		`function Get-LatestSeenClientCheck`,
		`[bool]$DeviceOnly = $false`,
		`if ($DeviceOnly -and -not (Test-DeviceClientCheckEvidence $clientCheck))`,
		`Get-LatestSeenClientCheck -ClientChecks (Get-ClientCheckEntries $BaseUrl) -DeviceOnly $true`,
		`function Wait-ForClientCheckEvidence`,
		`(Test-FreshClientCheck $clientCheck) -and $null -eq $pollSeenClientCheck`,
		`Start-Sleep -Seconds ([Math]::Min`,
		`Wait-ForClientCheckEvidence $BaseUrl $HoldSeconds $RequireDevice $RequireStandalone $RequireInteraction`,
		`$script:HoldStartedMs = $null`,
		`hold_started_ms=$script:HoldStartedMs`,
		`function Get-TailscaleHostName`,
		`tailscale status --self --json`,
		`function Get-DirectLanDeviceUrl`,
		`function Get-CandidateDeviceHosts`,
		`function Get-CandidatePriority`,
		`function Test-UsableDeviceHost`,
		`function Test-DeviceInterfaceName`,
		`InterfaceAlias`,
		`Test-DeviceInterfaceName ([string]$_.InterfaceAlias)`,
		`if ($hosts.Count -eq 0)`,
		`'vethernet'`,
		`'wsl'`,
		`Get-DirectLanDeviceUrl $BaseUrl`,
		`device_url_source=$script:DeviceUrlSource`,
		`node verify-api.mjs $BaseUrl`,
		`node verify-api.mjs $phoneUrl`,
		`Write-Report 'readyz=pass'`,
		`Write-Report 'public_readyz=pass'`,
		`Write-ReadinessCollectionErrors 'readyz' $ready`,
		`Write-ReadinessCollectionErrors 'public_readyz' $publicReady`,
		`Write-Report 'public_api_schema=pass'`,
		`$script:ExpectedDashboardBuild = ''`,
		`$publicStatus = Invoke-RestMethod -Method Get -Uri "$phoneUrl/api/status" -TimeoutSec 5`,
		`$script:ExpectedDashboardBuild = [string]$publicStatus.dashboard_build`,
		`Write-Report "dashboard_build=$script:ExpectedDashboardBuild"`,
		`Write-Report 'public_dashboard_assets=pass'`,
		`Open from the installed Home Screen Sysmon app on your device during the hold:`,
		`confirm the status strip shows app mode`,
		`device_hold_instruction=home_screen_open_status_strip_tap`,
		`Observed a fresh device dashboard client check during the deployed hold, but it was not in Home Screen standalone mode.`,
		`Observed a fresh device Home Screen status-strip tap during the deployed hold.`,
		`Observed a fresh device Home Screen dashboard client check, but it did not include the required status-strip tap.`,
		`Observed a fresh device dashboard client check, but it was not running the current dashboard build.`,
		`Write-Report 'device_client_seen=pass'`,
		`Write-Report 'device_client_seen=not_interactive'`,
		`Write-Report 'device_client_seen=stale_dashboard_build'`,
		`$script:InstalledDeviceHomeScreen = 'pass'`,
		`$script:InstalledDeviceHomeScreen = 'not_verified'`,
		`Write-Report "installed_device_home_screen=$script:InstalledDeviceHomeScreen"`,
		`Write-Report 'device_client_seen=not_standalone'`,
		`Write-Report 'device_client_seen=stale_client'`,
		`Write-Report 'device_client_seen=unexpected_client'`,
		`Write-Report 'device_client_seen=not_observed'`,
	} {
		if !strings.Contains(script, needle) {
			t.Fatalf("verify-deployed-windows.ps1 missing %q", needle)
		}
	}

	settingsStart := strings.Index(script, "function Test-SettingsSameOriginRoundTrip")
	settingsEnd := strings.Index(script, "function Test-ClientCheckSameOriginRoundTrip")
	if settingsStart < 0 || settingsEnd < 0 || settingsEnd <= settingsStart {
		t.Fatalf("verify-deployed-windows.ps1 missing settings roundtrip function boundaries")
	}
	settingsFunction := script[settingsStart:settingsEnd]
	for _, needle := range []string{
		`$statusAfterSettings = Invoke-RestMethod -Method Get -Uri "$Url/api/status" -TimeoutSec 5`,
		`$statusSettings = $statusAfterSettings.settings`,
		`settings status.thresholds.$key roundtrip mismatch`,
	} {
		if !strings.Contains(settingsFunction, needle) {
			t.Fatalf("Test-SettingsSameOriginRoundTrip missing %q", needle)
		}
	}
}

func TestWindowsDeployedVerifierWritesSingleStaleClientOutcome(t *testing.T) {
	data, err := os.ReadFile("verify-deployed-windows.ps1")
	if err != nil {
		t.Fatal(err)
	}
	script := string(data)
	start := strings.Index(script, "function Write-ClientCheckResult")
	end := strings.Index(script, "function Get-ClientCheckEntries")
	if start < 0 || end < 0 || end <= start {
		t.Fatalf("verify-deployed-windows.ps1 missing Write-ClientCheckResult boundaries")
	}

	resultFunction := script[start:end]
	const staleClientReport = `Write-Report 'device_client_seen=stale_client'`
	if count := strings.Count(resultFunction, staleClientReport); count != 1 {
		t.Fatalf("Write-ClientCheckResult has %d stale-client reports, want 1", count)
	}
}
